[package]
edition = "2021"
version = "0.1.0"
name = "replibyte"
authors = ["Qovery"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
uriparse = "0.6"
anyhow = "1.0.56"
serde_yaml = "0.8"
aws-config = "0.9.0"
aws-sdk-s3 = "0.9.0"
dump-parser = { path = "../dump-parser" }
clap = { version = "3.1", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
