version: '3'

services:
  source-mysql:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-u', 'root', '--password=password']
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./db/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  dest-mysql:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-u', 'root', '--password=password']
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3307:3306
