version: '3'

services:
  source-mysql:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-u', 'root', '--password=password']
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./db/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  dest-mysql:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-u', 'root', '--password=password']
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3307:3306
  bridge-minio:
    image: minio/minio:RELEASE.2023-02-27T18-10-45Z
    restart: always
    command: server --console-address ":9001" /data/minio/
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9000:9000
      - 9001:9001
  create-minio-bucket:
    image: minio/mc
    depends_on:
      - bridge-minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://bridge-minio:9000 minioadmin minioadmin;
      /usr/bin/mc rm -r --force myminio/replibyte-test;
      /usr/bin/mc mb myminio/replibyte-test;
      /usr/bin/mc policy download myminio/replibyte-test;
      exit 0;
      "
