on:
  release:
    types:
      - published
      - created

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build for linux
        run: |
          docker run --rm \
            --volume "${PWD}":/root/src \
            --workdir /root/src \
            joseluisq/rust-linux-darwin-builder:1.60.0 \
            sh -c "cargo build --release"

      - name: Prepare release
        run: |
          cd target/x86_64-unknown-linux-musl/release
          EVENT_DATA=$(cat "$GITHUB_EVENT_PATH")
          RELEASE_NAME=$(echo "$EVENT_DATA" | jq -r .release.tag_name)
          FILE=replibyte_${RELEASE_NAME}_x86_64-unknown-linux-musl
          sudo tar -czvf ${FILE}.tar.gz replibyte && sudo rm replibyte
          sudo touch ${FILE}.tar.gz.sha256sum && sudo chmod 777 ${FILE}.tar.gz.sha256sum
          sudo sha256sum "${FILE}.tar.gz" | cut -d ' ' -f 1 > ${FILE}.tar.gz.sha256sum

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-unknown-linux-musl/release/replibyte_*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          target: x86_64-pc-windows-gnu
          override: true

      - name: Build for windows
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y g++-mingw-w64-x86-64
          cargo build --all --release --target x86_64-pc-windows-gnu

      - name: Prepare release
        run: |
          cd target/x86_64-pc-windows-gnu/release
          EVENT_DATA=$(cat "$GITHUB_EVENT_PATH")
          RELEASE_NAME=$(echo "$EVENT_DATA" | jq -r .release.tag_name)
          FILE=replibyte_${RELEASE_NAME}_x86_64-pc-windows-gnu.exe
          sudo zip -9r ${FILE}.zip replibyte.exe && sudo rm replibyte.exe
          sudo touch ${FILE}.zip.sha256sum && sudo chmod 777 ${FILE}.zip.sha256sum
          sudo sha256sum "${FILE}.zip" | cut -d ' ' -f 1 > ${FILE}.zip.sha256sum

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-pc-windows-gnu/release/replibyte_*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build for mac
        run: |
          docker run --rm \
            --volume "${PWD}":/root/src \
            --workdir /root/src \
            joseluisq/rust-linux-darwin-builder:1.60.0 \
            sh -c "CC=o64-clang CXX=o64-clang++ cargo build --release --target x86_64-apple-darwin"

      - name: Prepare release
        id: prep
        run: |
          cd target/x86_64-apple-darwin/release
          EVENT_DATA=$(cat "$GITHUB_EVENT_PATH")
          RELEASE_NAME=$(echo "$EVENT_DATA" | jq -r .release.tag_name)
          FILE=replibyte_${RELEASE_NAME}_x86_64-apple-darwin
          sudo zip -9r ${FILE}.zip replibyte && sudo rm replibyte
          sudo touch ${FILE}.zip.sha256sum && sudo chmod 777 ${FILE}.zip.sha256sum
          CHECKSUM=$(sudo sha256sum "${FILE}.zip" | cut -d ' ' -f 1)
          echo "${CHECKSUM}" > ${FILE}.zip.sha256sum
          echo "::set-output name=sha256::${CHECKSUM}"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-apple-darwin/release/replibyte_*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      sha256: ${{ steps.prep.outputs.sha256 }}

  publish-on-homebrew:
    runs-on: ubuntu-latest
    needs: [build-mac]
    steps:
      - name: Extract version
        id: extract-version
        run: |
          printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"
      - uses: mislav/bump-homebrew-formula-action@v2
        if: "!contains(github.ref, '-')" # skip prereleases
        with:
          formula-name: replibyte
          homebrew-tap: Qovery/homebrew-replibyte
          download-url: https://github.com/Qovery/replibyte/releases/download/${{ steps.extract-version.outputs.tag-name }}/replibyte_${{ steps.extract-version.outputs.tag-name }}_x86_64-apple-darwin.zip
          download-sha256: ${{ needs.build-mac.outputs.sha256 }}
        env:
          COMMITTER_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
